### ISSUE TITLE
Make the phylogeny optional

### ISSUE THREAD

**Issue by ElDeveloper** [knightlab-analyses/regression-benchmarking#3]
If not specified, then we can skip UniFrac metrics.

**Comment by patrickimran** [comment]
Is there a way to specify optional outputs in the plugin setup or elsewhere?
Currently have `TypeError: Number of outputs must match number of output semantic types: 2 != 8`
It [doesn't seem like is possible](https://forum.qiime2.org/t/guidance-modifying-q2-vsearch-to-recover-uc-file/15009/4) so I'm unsure if the best approach would be to define a slightly different pipeline.

**Comment by ElDeveloper** [comment]
Oh that's true! You could always save an empty tree?
