### ISSUE TITLE
Produce rarefied and un-rarefied table

### ISSUE THREAD

**Issue by ElDeveloper** [knightlab-analyses/regression-benchmarking#6]
From the preprocess pipeline.

**Comment by patrickimran** [comment]
Updating to say rarefaction+tree should both be an option - rarefaction and beta diversity distances may not make sense/will not be necessary for different feature tables. We should consider including multiple options for normalization, or just exclude any normalization from mlab.

**Comment by ElDeveloper** [comment]
@patrickimran are you referring to #3 instead?
